### PR TITLE
Add instructions button

### PR DESCRIPTION
**Pull request by user833**

### CODE REVIEW

**Review by ElementMo — COMMENTED** [review]
Good
Finish the Instruction Page Soon ~

**Review by ElementMo — COMMENTED** [review]
In the instruction page,
"corn teacher.png" image is missing

**Comment by EgMan** [comment]
missing corn teacher png is resolved

**Review by WayneLee97 — APPROVED** [review]

**Review by EgMan — APPROVED** [review]

**Review by ElementMo — APPROVED** [review]
Cool with it.

**Pull request merged**
